name = "HybridDynamics"
uuid = "6b3332bd-f7e8-4dca-bbbd-4128c12b268e"
authors = ["William Clark"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
